CREATE TABLE IF NOT EXISTS `b_mibix_yam_general`
(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `profile_id` ENUM('YAMARKET') NOT NULL DEFAULT 'YAMARKET',
  `company` VARCHAR(255) NOT NULL,
  `salon` CHAR(1) NOT NULL DEFAULT 'N',
  `url` VARCHAR(100) NOT NULL DEFAULT '',
  `platform_version` CHAR(1) NOT NULL DEFAULT '',
  `agency` VARCHAR(100) NOT NULL DEFAULT '',
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `local_delivery_cost` VARCHAR(20) NOT NULL DEFAULT '',
  `do_cost` VARCHAR(20) NOT NULL DEFAULT '',
  `do_days` VARCHAR(20) NOT NULL DEFAULT '',
  `do_before` VARCHAR(20) NOT NULL DEFAULT '',
  `cpa` CHAR(1) NOT NULL DEFAULT '',
  `adult` CHAR(1) NOT NULL DEFAULT '',
  `utm` VARCHAR(255) NOT NULL DEFAULT '',
  `step_limit` VARCHAR(20) NOT NULL DEFAULT '',
  `step_path` VARCHAR(255) NOT NULL DEFAULT '',
  `step_interval_run` VARCHAR(20) NOT NULL DEFAULT '',
  `step_interval_type` ENUM('MIN','HOUR','DAY','WEEK','MONTH') NOT NULL DEFAULT 'MIN',
  `currency_rate` ENUM('RUB','BYR','UAH','KZT') NOT NULL DEFAULT 'RUB',
  `currency_rub` VARCHAR(10) NOT NULL DEFAULT '',
  `currency_rub_plus` TINYINT (3) NOT NULL DEFAULT '0',
  `currency_byr` VARCHAR(10) NOT NULL DEFAULT '',
  `currency_byr_plus` TINYINT (3) NOT NULL DEFAULT '0',
  `currency_uah` VARCHAR(10) NOT NULL DEFAULT '',
  `currency_uah_plus` TINYINT (3) NOT NULL DEFAULT '0',
  `currency_kzt` VARCHAR(10) NOT NULL DEFAULT '',
  `currency_kzt_plus` TINYINT (3) NOT NULL DEFAULT '0',
  `currency_usd` VARCHAR(10) NOT NULL DEFAULT '',
  `currency_usd_plus` TINYINT (3) NOT NULL DEFAULT '0',
  `currency_eur` VARCHAR(10) NOT NULL DEFAULT '',
  `currency_eur_plus` TINYINT (3) NOT NULL DEFAULT '0',
  `active` CHAR(1) NOT NULL DEFAULT 'Y', /* Активность */
  `date_insert`	DATETIME NOT NULL,
	`date_update` DATETIME NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `b_mibix_yam_datasource`
(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `shop_id` INT(11) NULL REFERENCES `b_mibix_yam_general` (id),
  `site_id` VARCHAR(100) NOT NULL DEFAULT '',
  `iblock_type` VARCHAR(100) NOT NULL,
  `iblock_id` INT(11) NOT NULL,
  `name_data` VARCHAR(255) NOT NULL,
  `include_sections` TEXT NOT NULL DEFAULT '',
  `exclude_sections` TEXT NOT NULL DEFAULT '',
  `include_items` TEXT NOT NULL DEFAULT '',
  `exclude_items` TEXT NOT NULL DEFAULT '',
  `include_subsection` CHAR(1) NOT NULL DEFAULT 'Y',
  `include_sku` CHAR(1) NOT NULL DEFAULT 'Y',
  `dpurl_use_sku` CHAR(1) NOT NULL DEFAULT 'Y',
  `filters` TEXT NOT NULL DEFAULT '',
  `active` CHAR(1) NOT NULL DEFAULT 'Y',
  `date_insert`	DATETIME	NOT NULL,
	`date_update` DATETIME	NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `b_mibix_yam_classific_categories`
(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `b_mibix_yam_market_categories`
(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_category` VARCHAR(255) NOT NULL,
  `parent_id` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `b_mibix_yam_steps_load`
(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `in_proccess` CHAR(1) NOT NULL DEFAULT 'N',
  `in_blocked` CHAR(1) NOT NULL DEFAULT 'N',
  `last_run_time` DATETIME NULL,
  `last_step_time` DATETIME NULL,
  `rule_id` INT(11) NOT NULL,
  `iblock_id` INT(11) NOT NULL,
  `element_id` INT(11) NOT NULL,
  `sku_iblock_id` INT(11) NOT NULL,
  `sku_element_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `b_mibix_yam_rules`
(
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `datasource_id` INT(11) NULL REFERENCES `b_mibix_yam_datasource` (id),
  `active` CHAR(1) NOT NULL DEFAULT 'Y',
  `type` VARCHAR(100) NOT NULL,
  `name_rule` VARCHAR(255) NOT NULL, /*название правила*/
  `category_id` INT(11) NOT NULL DEFAULT '0' REFERENCES `b_mibix_yam_classific_categories` (id),
  `market_category_id` TEXT NOT NULL DEFAULT '',
  `available` VARCHAR(100) NOT NULL DEFAULT 'true',
  `bid` VARCHAR(100) NOT NULL DEFAULT '',
  `cbid` VARCHAR(100) NOT NULL DEFAULT '',
  `url` CHAR(1) NOT NULL DEFAULT 'Y',
  `price` VARCHAR(100) NOT NULL DEFAULT '',
  `price_optimal` CHAR(1) NOT NULL DEFAULT 'Y',
  `price_currency` VARCHAR(20) NOT NULL DEFAULT '',
  `oldprice` VARCHAR(100) NOT NULL DEFAULT '',
  `oldprice_optimal` CHAR(1) NOT NULL DEFAULT 'Y',
  `picture` VARCHAR(100) NOT NULL DEFAULT '',
  `typeprefix` VARCHAR(100) NOT NULL DEFAULT '',
  `model` VARCHAR(100) NOT NULL DEFAULT '',
  `store` VARCHAR(100) NOT NULL DEFAULT '',
  `pickup` VARCHAR(100) NOT NULL DEFAULT '',
  `delivery` VARCHAR(100) NOT NULL DEFAULT '',
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `description` VARCHAR(100) NOT NULL DEFAULT '',
  `description_frm` CHAR(1) NOT NULL DEFAULT 'N',
  `vendor` VARCHAR(100) NOT NULL DEFAULT '',
  `vendorcode` VARCHAR(100) NOT NULL DEFAULT '',
  `local_delivery_cost` VARCHAR(100) NOT NULL DEFAULT '',
  `sales_notes` VARCHAR(100) NOT NULL DEFAULT '',
  `manufacturer_warranty` VARCHAR(100) NOT NULL DEFAULT '',
  `seller_warranty` VARCHAR(100) NOT NULL DEFAULT '',
  `country_of_origin` VARCHAR(100) NOT NULL DEFAULT '',
  `adult` VARCHAR(100) NOT NULL DEFAULT '',
  `downloadable` VARCHAR(100) NOT NULL DEFAULT '',
  `rec` TEXT NOT NULL DEFAULT '',
  `age` VARCHAR(100) NOT NULL DEFAULT '',
  `ageunit` VARCHAR(100) NOT NULL DEFAULT '',
  `barcode` TEXT NOT NULL DEFAULT '',
  `expiry` VARCHAR(100) NOT NULL DEFAULT '',
  `weight` VARCHAR(100) NOT NULL DEFAULT '',
  `dimensions` VARCHAR(100) NOT NULL DEFAULT '',
  `param` TEXT NOT NULL DEFAULT '',
  `deliveryoptions` TEXT NOT NULL DEFAULT '',
  `outlets` TEXT NOT NULL DEFAULT '',
  `cpa` VARCHAR(100) NOT NULL DEFAULT '',
  `author` VARCHAR(100) NOT NULL DEFAULT '',
  `publisher` VARCHAR(100) NOT NULL DEFAULT '',
  `series` VARCHAR(100) NOT NULL DEFAULT '',
  `year` VARCHAR(100) NOT NULL DEFAULT '',
  `isbn` VARCHAR(100) NOT NULL DEFAULT '',
  `volume` VARCHAR(100) NOT NULL DEFAULT '',
  `part` VARCHAR(100) NOT NULL DEFAULT '',
  `language` VARCHAR(100) NOT NULL DEFAULT '',
  `binding` VARCHAR(100) NOT NULL DEFAULT '',
  `page_extent` VARCHAR(100) NOT NULL DEFAULT '',
  `table_of_contents` VARCHAR(100) NOT NULL DEFAULT '',
  `performed_by` VARCHAR(100) NOT NULL DEFAULT '',
  `performance_type` VARCHAR(100) NOT NULL DEFAULT '',
  `format` VARCHAR(100) NOT NULL DEFAULT '',
  `storage` VARCHAR(100) NOT NULL DEFAULT '',
  `recording_length` VARCHAR(100) NOT NULL DEFAULT '',
  `artist` VARCHAR(100) NOT NULL DEFAULT '',
  `title` VARCHAR(100) NOT NULL DEFAULT '',
  `media` VARCHAR(100) NOT NULL DEFAULT '',
  `starring` VARCHAR(100) NOT NULL DEFAULT '',
  `director` VARCHAR(100) NOT NULL DEFAULT '',
  `originalname` VARCHAR(100) NOT NULL DEFAULT '',
  `country` VARCHAR(100) NOT NULL DEFAULT '',
  `worldregion` VARCHAR(100) NOT NULL DEFAULT '',
  `region` VARCHAR(100) NOT NULL DEFAULT '',
  `days` VARCHAR(100) NOT NULL DEFAULT '',
  `datatour` VARCHAR(100) NOT NULL DEFAULT '',
  `hotel_stars` VARCHAR(100) NOT NULL DEFAULT '',
  `room` VARCHAR(100) NOT NULL DEFAULT '',
  `meal` VARCHAR(100) NOT NULL DEFAULT '',
  `included` VARCHAR(100) NOT NULL DEFAULT '',
  `transport` VARCHAR(100) NOT NULL DEFAULT '',
  `place` VARCHAR(100) NOT NULL DEFAULT '',
  `hall_plan` VARCHAR(100) NOT NULL DEFAULT '',
  `date` VARCHAR(100) NOT NULL DEFAULT '',
  `is_premiere` VARCHAR(100) NOT NULL DEFAULT '',
  `is_kids` VARCHAR(100) NOT NULL DEFAULT '',
  `adt_dress_group_id` CHAR(1) NOT NULL DEFAULT 'N',
  `date_insert`	DATETIME	NOT NULL,
  `date_update` DATETIME	NULL,
  PRIMARY KEY (`id`)
);